CREATE OR REPLACE FUNCTION averages(
  p_lat   double precision,
  p_lon   double precision,
  p_start timestamptz,
  p_end   timestamptz
)
RETURNS TABLE (
  lat double precision,
  lon double precision,
  date timestamptz,
  air_temperature real,
  humidity real,
  pressure real,
  zonal_wind_speed real,
  meridional_wind_speed real,
  longwave_radiation real,
  convective_precipitation real,
  potential_energy real,
  potential_evaporation real,
  precipitation real,
  shortwave_radiation real,
  relative_humidity real,
  wind_speed real,
  nswrs real,
  nlwrs real,
  dswrf real,
  dlwrf real,
  lhtfl real,
  shtfl real,
  gflux real,
  snohf real,
  asnow real,
  arain real,
  evp real,
  ssrun real,
  bgrun real,
  snom real,
  avsft real,
  albdo real,
  weasd real,
  snowc real,
  snod real,
  tsoil real,
  soilm1 real,
  soilm2 real,
  soilm3 real,
  soilm4 real,
  soilm5 real,
  mstav1 real,
  mstav2 real,
  soilm6 real,
  evcw real,
  trans real,
  evbs real,
  sbsno real,
  cnwat real,
  acond real,
  ccond real,
  lai real,
  veg real
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    lat,
    lon,
    gs AS date,
    air_temperature,
    humidity,
    pressure,
    zonal_wind_speed,
    meridional_wind_speed,
    longwave_radiation,
    convective_precipitation,
    potential_energy,
    potential_evaporation,
    precipitation,
    shortwave_radiation,
    relative_humidity,
    wind_speed,
    nswrs,
    nlwrs,
    dswrf,
    dlwrf,
    lhtfl,
    shtfl,
    gflux,
    snohf,
    asnow,
    arain,
    evp,
    ssrun,
    bgrun,
    snom,
    avsft,
    albdo,
    weasd,
    snowc,
    snod,
    tsoil,
    soilm1,
    soilm2,
    soilm3,
    soilm4,
    soilm5,
    mstav1,
    mstav2,
    soilm6,
    evcw,
    trans,
    evbs,
    sbsno,
    cnwat,
    acond,
    ccond,
    lai,
    veg
  FROM generate_series(
    date_trunc('hour', p_start),
    date_trunc('hour', p_end),
    interval '1 hour'
  ) AS gs
  INNER JOIN (
    SELECT
      AVG(lat) AS lat,
      AVG(lon) AS lon,
      MAX(date) AS date,
      AVG(air_temperature) AS air_temperature,
      AVG(humidity) AS humidity,
      AVG(pressure) AS pressure,
      AVG(zonal_wind_speed) AS zonal_wind_speed,
      AVG(meridional_wind_speed) AS meridional_wind_speed,
      AVG(longwave_radiation) AS longwave_radiation,
      AVG(convective_precipitation) AS convective_precipitation,
      AVG(potential_energy) AS potential_energy,
      AVG(potential_evaporation) AS potential_evaporation,
      AVG(precipitation) AS precipitation,
      AVG(shortwave_radiation) AS shortwave_radiation,
      AVG(relative_humidity) AS relative_humidity,
      AVG(wind_speed) AS wind_speed,
      AVG(nswrs) AS nswrs,
      AVG(nlwrs) AS nlwrs,
      AVG(dswrf) AS dswrf,
      AVG(dlwrf) AS dlwrf,
      AVG(lhtfl) AS lhtfl,
      AVG(shtfl) AS shtfl,
      AVG(gflux) AS gflux,
      AVG(snohf) AS snohf,
      AVG(asnow) AS asnow,
      AVG(arain) AS arain,
      AVG(evp) AS evp,
      AVG(ssrun) AS ssrun,
      AVG(bgrun) AS bgrun,
      AVG(snom) AS snom,
      AVG(avsft) AS avsft,
      AVG(albdo) AS albdo,
      AVG(weasd) AS weasd,
      AVG(snowc) AS snowc,
      AVG(snod) AS snod,
      AVG(tsoil) AS tsoil,
      AVG(soilm1) AS soilm1,
      AVG(soilm2) AS soilm2,
      AVG(soilm3) AS soilm3,
      AVG(soilm4) AS soilm4,
      AVG(soilm5) AS soilm5,
      AVG(mstav1) AS mstav1,
      AVG(mstav2) AS mstav2,
      AVG(soilm6) AS soilm6,
      AVG(evcw) AS evcw,
      AVG(trans) AS trans,
      AVG(evbs) AS evbs,
      AVG(sbsno) AS sbsno,
      AVG(cnwat) AS cnwat,
      AVG(acond) AS acond,
      AVG(ccond) AS ccond,
      AVG(lai) AS lai,
      AVG(veg) AS veg
    FROM weather
    WHERE
      lat = p_lat AND lon = p_lon AND
      date BETWEEN (NOW() + INTERVAL '-4 years') AND NOW()
    GROUP BY TO_CHAR(date, 'MM-DD"T"HH24:00')
  ) w
  ON TO_CHAR(gs, 'MM-DD"T"HH24:00') = TO_CHAR(w.date, 'MM-DD"T"HH24:00')
  ORDER BY gs;
$$;

select * from averages(35, -80.875, '2020-01-01', '2020-01-02 23:59:59+00') order by date;

select date, precipitation from averages(35, -80.875, '2020-01-01', '2020-01-02 23:59:59+00') order by date;
select date, precipitation from averages(35, -80.875, '2013-01-01', '2013-01-02 23:59:59+00') order by date;
select date, precipitation from averages(35, -80.875, '2030-01-01', '2030-01-02 23:59:59+00') order by date;
select date, precipitation from averages(35, -80.875, '2026-12-31', '2027-01-02 23:59:59+00') order by date;